In [1]:
!conda list

# packages in environment at /home/main/anaconda2:
#
alabaster                 0.7.7                    py27_0  
anaconda                  4.0.0               np110py27_0  
anaconda-client           1.4.0                    py27_0  
anaconda-navigator        1.1.0                    py27_0  
argcomplete               1.0.0                    py27_1  
astropy                   1.1.2               np110py27_0  
babel                     2.2.0                    py27_0  
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0  
beautifulsoup4            4.4.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.9.1                    py27_0  
bokeh                     0.11.1                   py27_0  
boto                      2.39.0                   py27_0  
bottleneck                1.0.0               np

In [5]:
import pandas as pd
import numpy as np

In [13]:
df1 = pd.DataFrame(np.array([[1,2,3,4],[5,6,7,8],[9,8,10,11],[16,45,67,88]]))

In [14]:
df1

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9   8  10  11
3  16  45  67  88

In [15]:
df1.index= ["A1","A2","A3","A4"]
df1

0   1   2   3
A1   1   2   3   4
A2   5   6   7   8
A3   9   8  10  11
A4  16  45  67  88

In [17]:
df1.columns= ["X1","X2","X3","X4"]
df1

X1  X2  X3  X4
A1   1   2   3   4
A2   5   6   7   8
A3   9   8  10  11
A4  16  45  67  88

In [45]:
df1.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  8, 10, 11],
       [16, 45, 67, 88]])

In [25]:
arr1 = np.array(df1)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  8, 10, 11],
       [16, 45, 67, 88]])

In [29]:
arr1.dtype

dtype('int64')

In [19]:
list(df1)

['X1', 'X2', 'X3', 'X4']

In [22]:
df1.columns

Index([u'X1', u'X2', u'X3', u'X4'], dtype='object')

In [23]:
list(df1.columns)

['X1', 'X2', 'X3', 'X4']

How to use sklearn and pandas together:
- read data into a Pandas DataFrame
- Use native Pandas features to process text features to numerical ones:
  * Use the extremely convenient "dummies" feature of the Pandas library to convert categorical features to binary ones. (One-Hot encoding). 
  * Scikit has it's own One-Hot Encoding routine but it only works with integers (Features with categories like 1,2,3 rather than 'a','b','c'). Pandas can digest anything thrown at it.
- Finally, explicitly cast the DataFrame into a numpy array which can be used  by the scikit-learn API. 
- Note that at this point you lose your feature labels (Headers), so it would be difficult to keep track of the features if you use the "feature-importance" routine in scikit-learn. 
- save the headers before casting the data-frame into a numpy array.
> list(DataFrame1)     # prints out the headers into a nice list

In [52]:
dfmixed0 = pd.DataFrame([[1,2,3,4],[5,6,7,8],[9,8,10,11]])
dfmixed0

0  1   2   3
0  1  2   3   4
1  5  6   7   8
2  9  8  10  11

In [53]:
dfmixed0.values[:,:-1]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9,  8, 10]])

In [62]:
dfmixed1 = pd.DataFrame([[1,2,3,np.nan],[5,6,7,8],[9,8,10,11]])
dfmixed1

0  1   2     3
0  1  2   3   NaN
1  5  6   7   8.0
2  9  8  10  11.0

In [63]:
dfmixed1.values[:,:-1]

array([[  1.,   2.,   3.],
       [  5.,   6.,   7.],
       [  9.,   8.,  10.]])

In [71]:
dfmixed1.values[:,:-1].astype(np.float32)

array([[  1.,   2.,   3.],
       [  5.,   6.,   7.],
       [  9.,   8.,  10.]], dtype=float32)

In [68]:
float

float

In [56]:
dfmixed2 = pd.DataFrame([[1,2,3,'NaN'],[5,6,7,8],[9,8,10,11],['a','b','c','d']])
dfmixed2

0  1   2    3
0  1  2   3  NaN
1  5  6   7    8
2  9  8  10   11
3  a  b   c    d

In [72]:
dfmixed2.values[:,:-1]

array([[1, 2, 3],
       [5, 6, 7],
       [9, 8, 10],
       ['a', 'b', 'c']], dtype=object)

In [60]:
dfmixed2.values[:,:-1].astype(float)

ValueError: could not convert string to float: c